spring.datasource.url=jdbc:postgresql://localhost:5432/CrisisManagement
spring.datasource.username=rabiausul
spring.datasource.password=Rabia89.

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
app.seeder.enabled=false
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect

